apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: user-service
  labels:
    app.kubernetes.io/name: user-service
type: Opaque
stringData:
  MYSQL_USER: "xgame"
  MYSQL_PASSWORD: "CHANGE_ME"
  MYSQL_HOST: "mysql.user-service.svc.cluster.local"
  MYSQL_DATABASE: "bobby_test"
  REDIS_PASSWORD: ""
  JWT_SECRET: "CHANGE_ME_USE_A_LONG_RANDOM_STRING"
