apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: user-service
  labels:
    app.kubernetes.io/name: user-service
type: Opaque
stringData:
  MYSQL_DSN: "xgame:CHANGE_ME@tcp(mysql.user-service.svc.cluster.local:3306)/bobby_test?charset=utf8mb4&loc=Asia%2FShanghai&parseTime=true&timeout=5s&readTimeout=2s&writeTimeout=2s"
  JWT_SECRET: "CHANGE_ME_USE_A_LONG_RANDOM_STRING"
