apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.mysqlDsn }}
  MYSQL_DSN: {{ .Values.secret.mysqlDsn | quote }}
  {{- end }}
  JWT_SECRET: {{ required "A valid .Values.secret.jwtSecret is required" .Values.secret.jwtSecret | quote }}
