apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.mysqlDsn }}
  MYSQL_DSN: {{ .Values.secret.mysqlDsn | quote }}
  {{- else }}
  {{- if .Values.secret.mysqlHost }}
  MYSQL_HOST: {{ .Values.secret.mysqlHost | quote }}
  {{- end }}
  {{- if .Values.secret.mysqlPort }}
  MYSQL_PORT: {{ .Values.secret.mysqlPort | quote }}
  {{- end }}
  {{- if .Values.secret.mysqlUser }}
  MYSQL_USER: {{ .Values.secret.mysqlUser | quote }}
  {{- end }}
  {{- if .Values.secret.mysqlPassword }}
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword | quote }}
  {{- end }}
  {{- if .Values.secret.mysqlDatabase }}
  MYSQL_DATABASE: {{ .Values.secret.mysqlDatabase | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  JWT_SECRET: {{ required "A valid .Values.secret.jwtSecret is required" .Values.secret.jwtSecret | quote }}
